### ISSUE TITLE
<pre>Cannot POST /invoicing/createStripeInvoices</pre>

### ISSUE THREAD

**Issue by ferrymul7** [SAP-samples/btp-create-api-integrations#12]
Hi Team, i got the below error when issueing a curl command to test the deployment with stripe integration. Please advise what is missing. Thanks, Ferry

ferrymul@909c4acf1983 cron-job % kubectl --namespace=default run curl --image=curlimages/curl -i --tty -- sh
If you don't see a command prompt, try pressing enter.
~ $ curl -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices' \
> --header 'Content-Type: application/json' \
> --data-raw '{ 
>     "month": "11",
>     "year": "2024"
> }'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices</pre>
</body>
</html>
~ $

**Comment by jmsrpp** [comment]
Hi @ferrymul7 - we will need the pod logs from your deployed application to troubleshoot this. Please attach them here.

**Comment by ferrymul7** [comment]
@jmsrpp , i got 2 pods, curl pods give this log:
~ $ [6n ~ $ [J ~ $ [Jcurl -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month":"11", "year":"2024" }'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices</pre>
</body>
</html>

the other btp-invoicing-srv-7c48d874f7-4fr59 pod, doesn't have any logs generated.

Please advise.

**Comment by ferrymul7** [comment]
hi @jmsrpp , I deleted the pod and recreating them in trial using command "npm run build-deploy:kyma --image_name=ferrymul/btp-invoicing --namespace=trial" with success build and deploy

> btp-invoicing@1.0.0 deploy:kyma
> cross-var helm upgrade --install btp-invoicing ./chart --namespace=$npm_config_namespace

Release "btp-invoicing" does not exist. Installing it now.
NAME: btp-invoicing
LAST DEPLOYED: Tue Nov 19 10:20:01 2024
NAMESPACE: trial
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing btp-invoicing version 1.0.0.

The release "btp-invoicing" is installed in namespace "trial".

Your services are available at:
  - https://btp-invoicing-srv-trial.

******
Now i see the following problems in the pod events. The pod status is "ContainerCreating"

Successfully assigned trial/btp-invoicing-srv-7c48d874f7-xlfz7 to ip-10-250-1-13.ec2.internal
MountVolume.SetUp failed for volume "auth-secret" : secret "btp-invoicing-srv-auth" not found
MountVolume.SetUp failed for volume "destinations-secret" : secret "btp-invoicing-srv-destinations" not found

Please advise.

**Comment by jmsrpp** [comment]
The secrets should be mounted from the helm chart. Please double check that the helm matches what we have in the repo, aside from the version changes we implemented earlier in this issue.

**Comment by ferrymul7** [comment]
@jmsrpp , i re-clone the stripe branch and re-run all the fixes to make the build phase successful, but still have the same problem. Can you help to point out which files within helm chart that need to be fixed ? Thank you.

**Comment by jmsrpp** [comment]
Hi @ferrymul7 - sorry you're encountering all these issues. 

this [values.yaml](https://github.com/SAP-samples/btp-create-api-integrations/blob/stripe/btp-invoicing/chart/values.yaml#L28-L38) has the service entries. It should result in xsuaa and destination service being created in your namespace. Please confirm.

the binding is defined [here](https://github.com/SAP-samples/btp-create-api-integrations/blob/stripe/btp-invoicing/chart/values.yaml#L5-L10)

If this still fails, you can try to recreate the helm chart using [cds add helm](https://cap.cloud.sap/docs/guides/deployment/to-kyma) which should pick up the bindings from the package.json

Also adding my colleague, @kay-schmitteckert in case he has any idea?

**Comment by ferrymul7** [comment]
@jmsrpp , i realized now that the secrets are always deployed in default namespace. I tried with trial namespace, it always fails as above. 

Anyway, i have now successfully deployed to default namespace, and below are the POD logs

******* btp-invoicing-srv-7c48d874f7-lw7q5 pod

{"level":"info","logger":"cds","timestamp":"2024-11-24T22:55:08.949Z","msg":"loaded model from 1 file(s):\n","type":"log"}
srv/csn.json
{"level":"info","logger":"cds","timestamp":"2024-11-24T22:55:15.188Z","msg":"using auth strategy {\n kind: 'xsuaa',\n impl: '../layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/auth/jwt-auth'\n} \n","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T22:55:19.786Z","msg":"serving InvoicingService { impl: 'srv/invoicing-service.js', path: '/odata/v4/invoicing' }","type":"log"}
{"level":"info","logger":"cds","timestamp":"2024-11-24T22:55:19.788Z","msg":"server listening on { url: 'http://localhost:8080' }","type":"log"}
[cds] - launched at 11/24/2024, 10:55:05 PM, version: 7.9.5, in: 14.044s

******* curl pod 
~ $ [6n ~ $ [J ~ $ [Jcurl -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "1
1", "year": "2024" }'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices()</pre>
</body>
</html>

I tried with the followings, but no luck:
curl -X POST 'btp-invoicing-srv:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
curl -X POST 'localhost:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
curl -X POST 'http://btp-invoicing-srv.default:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
curl -X POST 'http://btp-invoicing-srv.:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
curl -X POST 'http://localhost:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'

Please advise.

**Comment by ferrymul7** [comment]
@kay-schmitteckert , Tried that and it still the same error. The problem here is that there is no log, and the error messages is unhelpful to point out what is the problem.

~ $ curl -X POST 'btp-invoicing-srv:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year"
: "2024" }'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices</pre>
</body>
</html>

**Comment by jmsrpp** [comment]
The error message isn’t helpful because it’s never making it to the Pod. CURL is succinctly telling us it cannot resolve the hostname you’re trying. It means you need to try some basic DNS, ping, etc. Check this stack thread for a similar problem. They do some lookups, use a verbose option when running CURL, and so on. Unable to use curl and service name from inside kubernetes podstackoverflow.comJim ***@***.*** Nov 25, 2024, at 12:20 AM, Ferry Mulyadi ***@***.***> wrote:﻿
@kay-schmitteckert , Tried that and it still the same error. The problem here is that there is no log, and the error messages is unhelpful to point out what is the problem.
~ $ curl -X POST 'btp-invoicing-srv:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year"
: "2024" }'




<title>Error</title>


Cannot POST /invoicing/createStripeInvoices

**Comment by ferrymul7** [comment]
@jmsrpp , i added -v in curl, and i see the following. It seems that it can connect, however it returns HTTP 404. i saw the build & deploy was successfully executed. Is there anything missing here ?

~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month":
 "11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host btp-invoicing-srv.default:8080 was resolved.
* IPv6: (none)
* IPv4: 10.111.68.119
*   Trying 10.111.68.119:8080...
* Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
* using HTTP/1.x
> POST /invoicing/createStripeInvoices() HTTP/1.1
> Host: btp-invoicing-srv.default:8080
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 bytes
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 172
< Date: Mon, 25 Nov 2024 18:22:16 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices()</pre>
</body>
</html>
* Connection #0 to host btp-invoicing-srv.default left intact

**Comment by jmsrpp** [comment]
It’s an action (not a function) so please remove the () from the URL and try again. Jim ***@***.*** Nov 25, 2024, at 11:27 AM, Ferry Mulyadi ***@***.***> wrote:﻿
@jmsrpp , i added -v in curl, and i see the following. It seems that it can connect, however it returns HTTP 404. i saw the build & deploy was successfully executed. Is there anything missing here ?
~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices()' --header 'Content-Type: application/json' --data-raw '{ "month":
"11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.

Host btp-invoicing-srv.default:8080 was resolved.
IPv6: (none)
IPv4: 10.111.68.119
Trying 10.111.68.119:8080...
Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
using HTTP/1.x


POST /invoicing/createStripeInvoices() HTTP/1.1
Host: btp-invoicing-srv.default:8080
User-Agent: curl/8.11.0
Accept: /
Content-Type: application/json
Content-Length: 33


upload completely sent off: 33 bytes
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 172
< Date: Mon, 25 Nov 2024 18:22:16 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<





<title>Error</title>


Cannot POST /invoicing/createStripeInvoices()


* Connection #0 to host btp-invoicing-srv.default left intact

**Comment by ferrymul7** [comment]
@jmsrpp , here is without the (). the service seems not available (404) ?

~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month": "
11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host btp-invoicing-srv.default:8080 was resolved.
* IPv6: (none)
* IPv4: 10.111.68.119
*   Trying 10.111.68.119:8080...
* Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
* using HTTP/1.x
> POST /invoicing/createStripeInvoices HTTP/1.1
> Host: btp-invoicing-srv.default:8080
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 bytes
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 170
< Date: Tue, 26 Nov 2024 00:16:41 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices</pre>
</body>
</html>
* Connection #0 to host btp-invoicing-srv.default left intact

**Comment by kay-schmitteckert** [comment]
sorry to bother you with all those tests, but could you try this:

'/odata/v4/invoicing/createStripeInvoices'

**Comment by ferrymul7** [comment]
No worry @kay-schmitteckert , i moved to the next phase now with new error in the srv pod log "Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function" .. Look forward for your advise. Thx

********* The request ******
~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/odata/v4/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "
month": "11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host btp-invoicing-srv.default:8080 was resolved.
* IPv6: (none)
* IPv4: 10.111.68.119
*   Trying 10.111.68.119:8080...
* Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
* using HTTP/1.x
> POST /odata/v4/invoicing/createStripeInvoices HTTP/1.1
> Host: btp-invoicing-srv.default:8080
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 bytes
< HTTP/1.1 204 No Content
< X-Powered-By: Express
< x-correlation-id: 5aaa1c22-dd33-4760-84f1-81b974a50423
< OData-Version: 4.0
< content-type: application/json;odata.metadata=minimal
< Date: Tue, 26 Nov 2024 06:46:09 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host btp-invoicing-srv.default left intact

*************** SRV Pod Logs ****

{"level":"info","logger":"odata","correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.0","accept":"*/*","content_type":"application/json","content_length":"33","request_size_b":"33","x_correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","timestamp":"2024-11-26T06:46:08.026Z","msg":"POST /odata/v4/invoicing/createStripeInvoices ","type":"log"}
{"level":"warn","logger":"remote","correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.0","accept":"*/*","content_type":"application/json;IEEE754Compatible=true","content_length":"33","request_size_b":"33","x_correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","timestamp":"2024-11-26T06:46:09.018Z","msg":"Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","stacktrace":["Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_r
process.processTicksAndRejections (node:internal/process/task_queues:95:5)","at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)","at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20)"],"statusCode":502,"reason":{"request":{"method":"GET","url":"/apiportal/api/1.0/Management.svc/Developers","headers":{"accept":"application/json,text/plain","x-correlation-id":"5aaa1c22-dd33-4760-84f1-81b974a50423"}},"correlationId":"5aaa1c22-dd33-4760-84f1-81b974a50423"},"type":"log"}
Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function
at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:234:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)
at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) {
statusCode: 502,
reason: TypeError: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function
at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:87:66
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:223:16)
at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)
at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) {
request: {
method: 'GET',
url: '/apiportal/api/1.0/Management.svc/Developers',
headers: [Object]
},
correlationId: '5aaa1c22-dd33-4760-84f1-81b974a50423'
}

**Comment by kay-schmitteckert** [comment]
> No worry @kay-schmitteckert , i moved to the next phase now with new error in the srv pod log "Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function" .. Look forward for your advise. Thx
> 
> ********* The request ****** ~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/odata/v4/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ " month": "11", "year": "2024" }' Note: Unnecessary use of -X or --request, POST is already inferred.
> 
> * Host btp-invoicing-srv.default:8080 was resolved.
> * IPv6: (none)
> * IPv4: 10.111.68.119
> * Trying 10.111.68.119:8080...
> * Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
> * using HTTP/1.x
> 
> > POST /odata/v4/invoicing/createStripeInvoices HTTP/1.1
> > Host: btp-invoicing-srv.default:8080
> > User-Agent: curl/8.11.0
> > Accept: _/_
> > Content-Type: application/json
> > Content-Length: 33
> 
> * upload completely sent off: 33 bytes
>   < HTTP/1.1 204 No Content
>   < X-Powered-By: Express
>   < x-correlation-id: 5aaa1c22-dd33-4760-84f1-81b974a50423
>   < OData-Version: 4.0
>   < content-type: application/json;odata.metadata=minimal
>   < Date: Tue, 26 Nov 2024 06:46:09 GMT
>   < Connection: keep-alive
>   < Keep-Alive: timeout=5
>   <
> * Connection #0 to host btp-invoicing-srv.default left intact
> 
> *************** SRV Pod Logs ****
> 
> {"level":"info","logger":"odata","correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.0","accept":"_/_","content_type":"application/json","content_length":"33","request_size_b":"33","x_correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","timestamp":"2024-11-26T06:46:08.026Z","msg":"POST /odata/v4/invoicing/createStripeInvoices ","type":"log"} {"level":"warn","logger":"remote","correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.0","accept":"_/_","content_type":"application/json;IEEE754Compatible=true","content_length":"33","request_size_b":"33","x_correlation_id":"5aaa1c22-dd33-4760-84f1-81b974a50423","timestamp":"2024-11-26T06:46:09.018Z","msg":"Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","stacktrace":["Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_r process.processTicksAndRejections (node:internal/process/task_queues:95:5)","at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)","at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20)"],"statusCode":502,"reason":{"request":{"method":"GET","url":"/apiportal/api/1.0/Management.svc/Developers","headers":{"accept":"application/json,text/plain","x-correlation-id":"5aaa1c22-dd33-4760-84f1-81b974a50423"}},"correlationId":"5aaa1c22-dd33-4760-84f1-81b974a50423"},"type":"log"} Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:234:31) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20) at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17) at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10) at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) { statusCode: 502, reason: TypeError: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:87:66 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:223:16) at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20) at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17) at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10) at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) { request: { method: 'GET', url: '/apiportal/api/1.0/Management.svc/Developers', headers: [Object] }, correlationId: '5aaa1c22-dd33-4760-84f1-81b974a50423' }

Actually the request with `/odata/v4` looks successful with 204 as status code. This confirms my assumption that there was an update of CAP to a version which involves the protocol in the path (`/odata/v4`). This means that all further requests to CAP will not work unless either 
a) `/odata/v4/` is added everywhere
or
b) the service path (in srv/*.cds modules) is set absolutely to e.g. “/invoicing” etc.

**Comment by ferrymul7** [comment]
Hi @kay-schmitteckert , i did option b, rebuild and deploy to kyma, but it still fails as below. Now i would like to try with Option A. can you help to point out what are the changes required ? Thanks.

******

~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host btp-invoicing-srv.default:8080 was resolved.
* IPv6: (none)
* IPv4: 10.111.68.119
*   Trying 10.111.68.119:8080...
* Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
* using HTTP/1.x
> POST /invoicing/createStripeInvoices HTTP/1.1
> Host: btp-invoicing-srv.default:8080
> User-Agent: curl/8.11.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 bytes
< HTTP/1.1 404 Not Found
< X-Powered-By: Express
< Content-Security-Policy: default-src 'none'
< X-Content-Type-Options: nosniff
< Content-Type: text/html; charset=utf-8
< Content-Length: 170
< Date: Wed, 27 Nov 2024 11:57:31 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /invoicing/createStripeInvoices</pre>
</body>
</html>
* Connection #0 to host btp-invoicing-srv.default left intact

**Comment by ferrymul7** [comment]
Hi @kay-schmitteckert , May i know the status of this ? I would like to understand if there is any estimated timeline so i can workaround this with our partner. Thanks

**Comment by jmsrpp** [comment]
Hi @ferrymul7 - The updated URL with /odata/v4 is the one you will need to use unless you specifically change the @path annotation in the CAP cds. The ```Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function``` is almost certainly the root cause, but please provide the results of the CURL with the updated URL. It seems like one of your project dependencies is now out of date:

https://github.com/SAP/cloud-sdk-js/issues/4982

Can you also post the dependencies from your package.json? It might be also worth deleting your package-lock.json and reinstalling the dependencies, or running ```npm update``` to ensure everything is aligned.

If the @sap-cloud-sdk/http-client and @sap-cloud-sdk/openapi have been updated from 3.4.0 respectively you would also need to regenerate the corresponding API clients:

https://sap.github.io/cloud-sdk/docs/js/v1/guides/upgrade-to-version-2

I'll also look for @kay-schmitteckert to provide his input when available.

**Comment by ferrymul7** [comment]
Happy New Year @jmsrpp , this morning, i changed back the invoicing-services.cds with @path : 'invoicing' .. and somehow without /odata/v4/ the curl call went in with HTTP 204. The error is now only the Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function.

I have run the npm update. As for @sap-cloud-sdk/http-client and @sap-cloud-sdk/openapi , they are still 3.4.0.

Do i still need to upgrade the cloud-sdk to 2.0.0 ? if yes, this will be a major undertaking .. i would not be able to do it given my capacity. Please advise.

**Comment by jmsrpp** [comment]
Hi @ferrymul7 - Sorry you ran into this but normalizing the SAP Cloud SDK versions is the way to fix this. From your output:

├─┬ @sap-cloud-sdk/http-client@3.4.0
│ ├─┬ @sap-cloud-sdk/connectivity@3.25.0
│ │ ├── @sap-cloud-sdk/resilience@3.25.0 deduped
│ │ ├── @sap-cloud-sdk/util@3.25.0 deduped

so you need these other dependencies updated to v 3.4.0 or you can try lowering the http-client version to 3.25.0 to match the rest of the dependencies. Happy to also take a PR to fix this, sorry that I don't have the bandwidth to attempt to replicate. I last fully tested the E2E Stripe scenario near the end of 2023 and checked in these dependencies successfully at that time.

**Comment by ferrymul7** [comment]
Hi @jmsrpp , i updated http-client version to 3.25.0, but unfortunately no luck. Let me try to update all of them to 3.4.0 as a second try.

├─┬ @sap-cloud-sdk/http-client@3.25.0
│ ├── @sap-cloud-sdk/connectivity@3.25.0 deduped
│ ├── @sap-cloud-sdk/resilience@3.25.0 deduped
│ ├── @sap-cloud-sdk/util@3.25.0 deduped

~ $ curl -v -X POST 'btp-invoicing-srv.default:8080/invoicing/createStripeInvoices' --header 'Content-Type: application/json' --data-raw '{ "month": "11", "year": "2024" }'
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host btp-invoicing-srv.default:8080 was resolved.
* IPv6: (none)
* IPv4: 10.111.68.119
*   Trying 10.111.68.119:8080...
* Connected to btp-invoicing-srv.default (10.111.68.119) port 8080
* using HTTP/1.x
> POST /invoicing/createStripeInvoices HTTP/1.1
> Host: btp-invoicing-srv.default:8080
> User-Agent: curl/8.11.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 bytes
< HTTP/1.1 204 No Content
< X-Powered-By: Express
< x-correlation-id: 4ddb46e8-be17-420f-bf5a-ffde2d0c4499
< OData-Version: 4.0
< content-type: application/json;odata.metadata=minimal
< Date: Mon, 27 Jan 2025 09:26:47 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host btp-invoicing-srv.default left intact

{"level":"info","logger":"odata","correlation_id":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.1","accept":"*/*","content_type":"application/json","content_length":"33","request_size_b":"33","x_correlation_id":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499","timestamp":"2025-01-27T09:26:46.799Z","msg":"POST /invoicing/createStripeInvoices ","type":"log"}
{"level":"warn","logger":"remote","correlation_id":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499","host":"btp-invoicing-srv.default:8080","user_agent":"curl/8.11.1","accept":"*/*","content_type":"application/json;IEEE754Compatible=true","content_length":"33","request_size_b":"33","x_correlation_id":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499","timestamp":"2025-01-27T09:26:47.466Z","msg":"Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","stacktrace":["Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function","at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:234:31)","at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)","at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)","at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20)"],"statusCode":502,"reason":{"request":{"method":"GET","url":"/apiportal/api/1.0/Management.svc/Developers","headers":{"accept":"application/json,text/plain","x-correlation-id":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499"}},"correlationId":"4ddb46e8-be17-420f-bf5a-ffde2d0c4499"},"type":"log"}
Error: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function
at run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:234:31)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)
at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) {
statusCode: 502,
reason: TypeError: Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function
at /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:87:66
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async run (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:223:16)
at async RemoteService.on_handler (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:20)
at async next (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:68:17)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/lib/srv/srv-dispatch.js:66:10)
at async RemoteService.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@sap/cds/libx/_runtime/remote/Service.js:277:20) {
request: {
method: 'GET',
url: '/apiportal/api/1.0/Management.svc/Developers',
headers: [Object]
},
correlationId: '4ddb46e8-be17-420f-bf5a-ffde2d0c4499'
}
